INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Gold1", "Finance", 100, "6/25/18", "6/25/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Gold2", "Finance", 1000, "6/25/18", "6/25/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Gold3", "Finance", 10000, "6/25/18", "6/25/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Gold4", "Finance", 100000, "6/25/18", "6/25/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Gold5", "Finance", 1000000, "6/25/18", "6/25/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Bitcoin1", "Finance", 10000000, "6/25/18", "6/25/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Bitcoin2", "Finance", 100000000, "6/25/18", "6/25/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Bitcoin3", "Finance", 1000000000, "6/25/18", "6/25/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Bitcoin4", "Finance", 100000000000, "6/25/18", "6/25/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Bitcoin5", "Finance", 1000000000000, "6/25/18", "6/25/20");

INSERT INTO users (name, age) VALUES ("Goldsmith1", 1000);
INSERT INTO users (name, age) VALUES ("Goldsmith2", 1000);
INSERT INTO users (name, age) VALUES ("Goldsmith3", 1000);
INSERT INTO users (name, age) VALUES ("Goldsmith4", 1000);
INSERT INTO users (name, age) VALUES ("Goldsmith5", 1000);
INSERT INTO users (name, age) VALUES ("Goldsmith6", 1000);
INSERT INTO users (name, age) VALUES ("Goldsmith7", 1000);
INSERT INTO users (name, age) VALUES ("Goldsmith8", 1000);
INSERT INTO users (name, age) VALUES ("Goldsmith9", 1000);
INSERT INTO users (name, age) VALUES ("Goldsmith10", 1000);
INSERT INTO users (name, age) VALUES ("Bitsmith1", 5);
INSERT INTO users (name, age) VALUES ("Bitsmith2", 5);
INSERT INTO users (name, age) VALUES ("Bitsmith3", 5);
INSERT INTO users (name, age) VALUES ("Bitsmith4", 5);
INSERT INTO users (name, age) VALUES ("Bitsmith5", 5);
INSERT INTO users (name, age) VALUES ("Bitsmith6", 5);
INSERT INTO users (name, age) VALUES ("Bitsmith7", 5);
INSERT INTO users (name, age) VALUES ("Bitsmith8", 5);
INSERT INTO users (name, age) VALUES ("Bitsmith9", 5);
INSERT INTO users (name, age) VALUES ("Bitsmith10", 5);

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);

INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 5);

INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 15, 8);
